### ISSUE TITLE
how to deal with seasonality 

### ISSUE THREAD

**Issue by ghost** [cran/ARCensReg#1]
Hello, 

first of all thank you for the R package!

I tried ARCensReg() out using the phosphorus data (up to observation 119). 
Given that, I first checked seasonality patterns via acf() and found that there is indeed seasonality at lag 6.

Although it's possible to estimate the ARCensReg model the convergence fails (default settings were used). 

I am now asking myself whether there is anything to be said against using the function only for data augmentation / imputation (thus, a low order of p to maintain convergence should be fine) and then estimating a separate time series model where seasonality is incorporated (seasonal arima)

Thank you in advance.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
